editions:
  win11-24h2:
    - id: professional
      label: Windows 11 Pro
    - id: professionaln
      label: Windows 11 Pro N
    - id: education
      label: Windows 11 Education
    - id: educationn
      label: Windows 11 Education N
    - id: proneducation
      label: Windows 11 Pro Education
    - id: proneducationn
      label: Windows 11 Pro Education N
    - id: proworstation
      label: Windows 11 Pro for Workstations
    - id: enterprise
      label: Windows 11 Enterprise
    - id: enterprisen
      label: Windows 11 Enterprise N
  win11-25h2:
    - id: professional
      label: Windows 11 Pro
    - id: enterprise
      label: Windows 11 Enterprise
    - id: iotenterprise
      label: Windows 11 IoT Enterprise LTSC
  win10-22h2:
    - id: professional
      label: Windows 10 Pro
    - id: enterprise
      label: Windows 10 Enterprise
    - id: iotenterprise
      label: Windows 10 IoT Enterprise LTSC
